version: "3.8"

services:
  api:
    container_name: product-road-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: product-road-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
